# Generated by Django 4.1.1 on 2022-10-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Здесь будет указан ингредиент', max_length=200, verbose_name='Название ингредиента')),
                ('measurement_unit', models.CharField(help_text='Здесь будет указано название единиц измерения', max_length=20, verbose_name='Название единиц измерения')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='IngredientRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Количество')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Здесь будет указано название рецепта', max_length=200, verbose_name='Название рецепта')),
                ('texts', models.TextField(help_text='Здесь будет указано описание рецепта', max_length=1000, verbose_name='Описание рецепта')),
                ('cooking_time', models.IntegerField(help_text='Укажите время приготовления в минутах', verbose_name='Время приготовления')),
                ('pub_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации')),
                ('image', models.ImageField(default=None, null=True, upload_to='recipes/images/')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Здесь будет указано название тэга', max_length=20, verbose_name='Название тэга')),
                ('slug', models.SlugField(help_text='К нему потом можно будет обращаться', unique=True, verbose_name='Это слаг, для тэга')),
                ('color', models.CharField(max_length=7)),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
            },
        ),
    ]
