# Generated by Django 4.1.1 on 2022-10-10 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Здесь будет указан ингредиент', max_length=200, verbose_name='Название ингредиента')),
                ('measurement_unit', models.CharField(help_text='Здесь будет указано название единиц измерения', max_length=20, verbose_name='Название единиц измерения')),
            ],
        ),
        migrations.CreateModel(
            name='QuantityIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='количество')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Здесь будет указано название тэга', max_length=20, verbose_name='Название тэга')),
                ('slug', models.SlugField(help_text='К нему потом можно будет обращаться', unique=True, verbose_name='Это слаг, для тэга')),
                ('color', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Здесь будет указано название рецепта', max_length=200, verbose_name='Название рецепта')),
                ('description', models.TextField(help_text='Здесь будет указано описание рецепта', max_length=1000, verbose_name='Описание рецепта')),
                ('pub_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL)),
                ('ingredient', models.ManyToManyField(help_text='Ингредиент рецепта', related_name='quantity_ingredient', to='recipes.quantityingredient', verbose_name='Ингредиент рецепта')),
                ('tag', models.ManyToManyField(help_text='Тэг рецепта', related_name='tags', to='recipes.tag', verbose_name='Тэг')),
            ],
        ),
    ]
