# Generated by Django 4.1.1 on 2022-10-13 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientrecipe',
            options={'verbose_name': 'Ингредиенты рецептов', 'verbose_name_plural': 'Ингредиенты рецептов'},
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='texts',
            new_name='text',
        ),
    ]
