# Generated by Django 4.1.1 on 2022-10-20 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_follow_follow_unique follow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
    ]
